############################### S3 output vars #################################

variable "notification_service_source_bucket_id" {
  description = "Name of the bucket where the source code zip will be stored"
  type        = string
}

################################ Pipeline vars #################################

variable "code_result_zip" { # Pipeline env TF_VAR_CODE_RESULT_ZIP
  description = "Zip file name generated by pipeline in the build process"
  type        = string
}

variable "lambda_file_zip_name" { # Pipeline env TF_VAR_LAMBDA_FILE_ZIP_NAME
  type        = string
}

variable "whatsapp_api_token" { # TF_VAR_WHATSAPP_API_TOKEN
  type        = string
}

variable "db_username" { # TF_VAR_DB_USERNAME
  type        = string
}
variable "db_password" { # TF_VAR_DB_PASSWORD
  type        = string
}
variable "db_name" { # TF_VAR_DB_NAME
  type        = string
}
variable "db_port" { # TF_VAR_DB_PORT
  type        = string
}
variable "db_uri" { # TF_VAR_DB_URI
  type        = string
}
variable "db_uri_args" { # TF_VAR_DB_URI_ARGS
  type        = string
}