name: Build zip artifacts for both Lambdas
on:
  workflow_call:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [notification-publisher, notification-dispatcher]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies and build for ${{ matrix.service }}
        run: |
          SERVICE=${{ matrix.service }}
          cd $SERVICE
          mkdir -p package
          pip install --upgrade pip
          pip install -r requirements.txt -t package/
          cp -r src package/
          cp lambda_function.py package/
          cd package
          zip -r "../../${SERVICE}.zip" .
          cd ../..

      - name: Upload artifact for ${{ matrix.service }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-deployment-package
          path: ${{ matrix.service }}.zip
          retention-days: 1