name: Setup infra
on:
  workflow_call:

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    env:
      TF_VAR_REGION: ${{ vars.REGION }}
      TF_VAR_TFSTATE_BUCKET_NAME: ${{ vars.TFSTATE_BUCKET_NAME }}
      TF_VAR_LAMBDA_FILE_ZIP_NAME: ${{ vars.LAMBDA_FILE_ZIP_NAME }}
      TF_VAR_WHATSAPP_API_TOKEN: ${{ secrets.WHATSAPP_API_TOKEN }}
      TF_VAR_DB_USERNAME: ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TF_VAR_DB_NAME: ${{ secrets.DB_NAME }}
      TF_VAR_DB_PORT: ${{ secrets.DB_PORT }}
      TF_VAR_DB_URI: ${{ secrets.DB_URI }}
      TF_VAR_DB_URI_ARGS: ${{ secrets.DB_URI_ARGS }}

    steps:
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Create Terraform state bucket if not exists
        run: |
          if aws s3api head-bucket --bucket "$TF_VAR_TFSTATE_BUCKET_NAME" 2>/dev/null; then
            echo "State bucket already exists"
          else
            echo "State bucket not found. Creating..."
            aws s3api create-bucket --bucket "$TF_VAR_TFSTATE_BUCKET_NAME" --region ${{ vars.REGION }}
            echo "State bucket created"
          fi
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false