name: Setup infra
on:
  workflow_call:

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "DEBUG"
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_publisher_source_code_zip: "notification-publisher.zip"
      TF_VAR_dispatcher_source_code_zip: "notification-dispatcher.zip"
      TF_VAR_publisher_source_code_lambda_s3_zip_name: "publisher-service"
      TF_VAR_dispatcher_source_code_lambda_s3_zip_name: "dispatcher-service"
      TF_VAR_tfstate_bucket_name: ${{ vars.TFSTATE_BUCKET_NAME }}
      TF_VAR_whatsapp_api_token: ${{ secrets.WHATSAPP_API_TOKEN }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_port: ${{ secrets.DB_PORT }}
      TF_VAR_db_uri: ${{ secrets.DB_URI }}
      TF_VAR_db_uri_args: ${{ secrets.DB_URI_ARGS }}

    steps:
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Create Terraform state bucket if not exists
        run: |
          if aws s3api head-bucket --bucket "$TF_VAR_tfstate_bucket_name" 2>/dev/null; then
            echo "State bucket already exists"
          else
            echo "State bucket not found. Creating..."
            aws s3api create-bucket --bucket "$TF_VAR_tfstate_bucket_name" --region ${{ vars.REGION }}
            echo "State bucket created"
          fi

      - name: Set up repository files
        uses: actions/checkout@v4

      - name: Download artifact for notification-publisher
        uses: actions/download-artifact@v4
        with:
          name: notification-publisher-deployment-package
          path: ./terraform

      - name: Download artifact for notification-dispatcher
        uses: actions/download-artifact@v4
        with:
          name: notification-dispatcher-deployment-package
          path: ./terraform
      
      - name: List downloaded files
        run: ls -R ./terraform
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init \
            -backend-config="bucket=$TF_VAR_tfstate_bucket_name" \
            -backend-config="key=terraform.state" \
            -backend-config="region=$TF_VAR_region"

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -input=false

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve -input=false