name: Orchestrator

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  infra:
    needs: build
    uses: ./.github/workflows/infra.yml
    secrets: inherit
