################################ Pipeline vars #################################

variable "code_result_zip" { # Pipeline env TF_VAR_CODE_RESULT_ZIP
  description = "Zip file name generated by pipeline in the build process"
  type        = string
}

variable "lambda_file_zip_name" { # Pipeline env TF_VAR_LAMBDA_FILE_ZIP_NAME
  type        = string
}
